version: '3'

services:
  web:
    build:
      context: .
      dockerfile: tests/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres
  redis:
    image: redis
