version: '3'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - /static
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
  nginx:
     image: nginx:alpine
     restart: always
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./staticfiles:/www/static
       - ./nginx:/etc/nginx/conf.d
       - /home/miles/cerfs:/cerfs
       - .:/app
     links:
       - web
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  data:
