# Generated by Django 2.0.2 on 2018-02-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_posted', models.TimeField(auto_now_add=True)),
                ('duration', models.TimeField()),
            ],
        ),
    ]
