# Generated by Django 2.0.2 on 2018-02-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20180212_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='researcher',
            new_name='responder',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='dispatcher',
            new_name='creator',
        ),
    ]
