# Generated by Django 2.0.2 on 2018-03-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
