# Generated by Django 2.0.2 on 2018-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='', max_length=100, verbose_name='When'),
            preserve_default=False,
        ),
    ]
