# Generated by Django 2.0.2 on 2018-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20180302_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='duration_value',
            field=models.IntegerField(default=6, verbose_name='Duration'),
        ),
    ]
